#!/bin/bash

xrandr --output DP-2-2 --mode 1680x1050 --pos 0x0     --rotate normal \
       --output DP-2-3 --mode 1680x1050 --pos 1680x0  --rotate normal \
       --output eDP-1  --mode 1920x1080 --pos 3360x15 --rotate normal

