#!/bin/bash

while true; do
  echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    ~/bin/ssh-add-persistently dev-test1 github bbkf2salesdashpro;
    ~/bin/guake-setup;
    exit 0;
  else
      echo "Refusing to setup your workstation because you are offline!";
      exit 255;
  fi
done
